"""Type stubs for the compiled extension module."""

from typing import Any

__version__: str

Level = tuple[int, int, int]
"""(price, qty, orders)"""

class OrderBook:
    """A price-time priority limit order book in integer ticks and lots."""

    def __init__(self, stp: str = "cancel_resting", emit_book_updates: bool = True) -> None: ...
    def submit(
        self,
        id: int,
        side: str,
        price: int,
        qty: int,
        owner: int = 0,
        order_type: str = "limit",
    ) -> list[dict[str, Any]]: ...
    def limit(
        self, id: int, side: str, price: int, qty: int, owner: int = 0
    ) -> list[dict[str, Any]]: ...
    def market(self, id: int, side: str, qty: int, owner: int = 0) -> list[dict[str, Any]]: ...
    def ioc(
        self, id: int, side: str, price: int, qty: int, owner: int = 0
    ) -> list[dict[str, Any]]: ...
    def fok(
        self, id: int, side: str, price: int, qty: int, owner: int = 0
    ) -> list[dict[str, Any]]: ...
    def post_only(
        self, id: int, side: str, price: int, qty: int, owner: int = 0
    ) -> list[dict[str, Any]]: ...
    def cancel(self, id: int) -> list[dict[str, Any]]: ...
    def amend(self, id: int, price: int, qty: int) -> list[dict[str, Any]]: ...
    def best_bid(self) -> tuple[int, int] | None: ...
    def best_ask(self) -> tuple[int, int] | None: ...
    def spread(self) -> int | None: ...
    def mid(self) -> float | None: ...
    def microprice(self) -> float | None: ...
    def depth_weighted_mid(self, levels: int = 5) -> float | None: ...
    def l2(self, depth: int = 10) -> dict[str, list[Level]]: ...
    def l3(self) -> dict[str, list[dict[str, Any]]]: ...
    def order(self, id: int) -> dict[str, Any] | None: ...
    def __len__(self) -> int: ...

class Ctx:
    """The strategy's handle on the simulation. Only valid inside the callback."""

    @property
    def now(self) -> int: ...
    @property
    def position(self) -> int: ...
    def best_bid(self) -> tuple[int, int] | None: ...
    def best_ask(self) -> tuple[int, int] | None: ...
    def mid(self) -> float | None: ...
    def microprice(self) -> float | None: ...
    def spread(self) -> int | None: ...
    def l2(self, depth: int = 5) -> dict[str, list[Level]]: ...
    def open_orders(self) -> list[dict[str, Any]]: ...
    def submit(self, side: str, price: int, qty: int, order_type: str = "limit") -> int: ...
    def limit(self, side: str, price: int, qty: int) -> int: ...
    def post_only(self, side: str, price: int, qty: int) -> int: ...
    def ioc(self, side: str, price: int, qty: int) -> int: ...
    def market(self, side: str, qty: int) -> int: ...
    def cancel(self, id: int) -> bool: ...
    def amend(self, id: int, price: int, qty: int) -> bool: ...
    def cancel_all(self) -> None: ...
    def stop(self) -> None: ...

def _run_backtest(
    config_json: str | None = None,
    config_path: str | None = None,
    strategy: object | None = None,
) -> str: ...
def _generate_feed(market_json: str | None = None) -> list[dict[str, Any]]: ...
